import { Avatar } from "./Avatar"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Avatar,
  "https://www.figma.com/design/WNOcZbybSn7dAGjTMimIsJ/Kido---DS?node-id=82%3A10891",
  {
    props: {
      initials: figma.string("✏️ initials"),
      lowerBadge: figma.boolean("lower badge"),
      upperBadge: figma.boolean("upper badge"),
      size: figma.enum("size", {
        "24": "24",
        "32": "32",
        "40": "40",
        "52": "52",
        "64": "64",
      }),
      type: figma.enum("type", {
        picture: "picture",
        initials: "initials",
      }),
      shape: figma.enum("shape", {
        circle: "circle",
        rounded: "rounded",
        square: "square",
      }),
      outline: figma.boolean("outline"),
    },
    example: (props) => <Avatar
      type={props.type}
      initials={props.initials}
      imageUrl={"image URL"}
      shape={props.shape}
      size={props.size}
      upperBadge={props.upperBadge}
      lowerBadge={props.lowerBadge}
    />,
  },
)
