import React from "react"
import { Checkbox, CheckboxState } from "./Checkbox"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Checkbox,
  "https://www.figma.com/design/WNOcZbybSn7dAGjTMimIsJ/Kido---DS?node-id=2186%3A14968",
  {
    props: {
      labelText: figma.string("✏️ label"),
      descriptionText: figma.string("✏️ description"),
      description: figma.boolean("description"),
      count: figma.boolean("count"),
      countText: figma.string("✏️ count"),
      icon: figma.boolean("icon"),
      iconIns: figma.instance("🔁 icon"),
      size: figma.enum("size", {
        m: "m",
        s: "s",
      }),
      state: figma.enum("state", {
        idle: "idle",
        hover: "hover",
        pressed: "pressed",
        focused: "focused",
        disabled: "disabled",
      }),
      selectionType: figma.enum("selection type", {
        unchecked: "unchecked",
        checked: "checked",
        indeterminate: "indeterminate",
      }),
      label: figma.boolean("label"),
    },
    example: (props) => <Checkbox />,
  },
)

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Checkbox,
  "https://www.figma.com/design/WNOcZbybSn7dAGjTMimIsJ/Kido---DS?node-id=2487%3A4224",
  {
    props: {
      labelText: figma.string("✏️ label"),
      descriptionText: figma.string("✏️ description"),
      description: figma.boolean("description"),
      count: figma.boolean("count"),
      countText: figma.string("✏️ count"),
      icon: figma.boolean("icon"),
      iconIns: figma.instance("🔁 icon"),
      label: figma.boolean("label"),
      size: figma.enum("size", {
        s: "s",
        m: "m",
      }),
      state: figma.enum("state", {
        disabled: "disabled",
        focused: "focused",
        pressed: "pressed",
        hover: "hover",
        idle: "idle",
      }),
      selectionType: figma.enum("selection type", {
        indeterminate: "indeterminate",
        checked: "checked",
        unchecked: "unchecked",
      }),
    },
    example: (props) => <Checkbox
      state={CheckboxState.Checked}
      onChange={() => { }}
      showLabel={props.label}
      labelText={props.labelText}
      showCount={props.count}
      count={props.countText}
      showDescription={props.description}
      description={props.descriptionText}
      showIcon={props.icon}
      icon={props.iconIns}
    />,
  },
)
