import React from "react"
import { Button } from "./Button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/WNOcZbybSn7dAGjTMimIsJ/Kido---DS?node-id=98%3A899",
  {
    props: {
      iconL: figma.instance("🔁 icon L"),
      iconR: figma.instance("🔁 icon R"),
      label: figma.string("✏️ label"),
      iconRBool: figma.boolean("icon R"),
      iconLBool: figma.boolean("icon L"),
      size: figma.enum("size", {
        s: "s",
        m: "m",
        l: "l",
      }),
      type: figma.enum("type", {
        contained: "contained",
        outlined: "outlined",
        ghost: "ghost",
      }),
      state: figma.enum("state", {
        idle: "idle",
        hover: "hover",
        pressed: "pressed",
        focused: "focused",
        disabled: "disabled",
        loading: "loading",
      }),
    },
    example: (props) => <Button size={props.size} variant={props.type} iconL={props.iconL} iconR={props.iconR}>
      {props.label}
    </Button>,
  },
)
